SELECT CUT.NAME, EMP.EMP_NM, DEP.ADDR
 FROM SQL_CUSTOMER CUT
 LEFT JOIN SQL_EMP EMP ON CUT.EMP = EMP.EMP_ID
 LEFT JOIN SQL_DEP DEP ON EMP.DEP = DEP.DEP


SELECT DATA.SERIAL_NUMBER, DATA.HYDROGEN, DATA.TURBIDITY, DATA.CHLORINE,SYSTEM.WATER_PURIFICATION_PLANT, SYSTEM.WATER_SUPPLY, REGIONS.TOWNSHIP, REGIONS.PLACE
FROM(
 SELECT PLACE, SERIAL_NUMBER, HYDROGEN, TURBIDITY, CHLORINE,WATER_SYSTEM
   FROM SQL_TAOYUAN_WATER
   WHERE
    (SERIAL_NUMBER BETWEEN 521 AND 529)
--    ORDER BY TURBIDITY ASC, SERIAL_NUMBER DESC;
   UNION 
 SELECT PLACE, SERIAL_NUMBER, HYDROGEN, TURBIDITY, CHLORINE, WATER_SYSTEM
   FROM SQL_TAOYUAN_WATER
   WHERE
   CHLORINE IN(0.76,0.77,0.66) AND HYDROGEN != 7.8 AND TURBIDITY = 0.6
   )DATA
--  ORDER BY ¿B«× ASC, §Ç¸¹ DESC;
  LEFT JOIN SQL_TAOYUAN_REGIONS REGIONS ON REGIONS.SERIAL = DATA.PLACE
  LEFT JOIN SQL_TAOYUAN_WATER_SYSTEM SYSTEM ON SYSTEM.SERIAL = DATA.WATER_SYSTEM
  ORDER BY TURBIDITY ASC, SERIAL_NUMBER DESC;