SELECT SERIAL_NUMBER AS 序號,
 HYDROGEN AS 氫離子濃度指數,
 TURBIDITY AS 濃度,
 CHLORINE AS 自由有效餘氯
  FROM SQL_TAOYUAN_WATER
  WHERE
   HYDROGEN IN(7.5, 8) AND CHLORINE >0.6 AND PLACE = 'T22';
   
SELECT DISTINCT PLACE AS 地點,
 SERIAL_NUMBER AS 序號,
 HYDROGEN AS 氫離子濃度指數,
 TURBIDITY AS 濁度,
 CHLORINE AS 自由有效餘氯
  FROM SQL_TAOYUAN_WATER
  WHERE
   (SERIAL_NUMBER BETWEEN 521 AND 529)
    OR
   (CHLORINE IN(0.76,0.77,0.66) AND HYDROGEN != 7.8 AND TURBIDITY = 0.6)
   ORDER BY TURBIDITY ASC, SERIAL_NUMBER DESC;
   
SELECT 地點, 序號,氫離子濃度指數, 濁度, 自由有效餘氯
FROM(
 SELECT PLACE AS 地點,
  SERIAL_NUMBER AS 序號,
  HYDROGEN AS 氫離子濃度指數,
  TURBIDITY AS 濁度,
  CHLORINE AS 自由有效餘氯
   FROM SQL_TAOYUAN_WATER
   WHERE
    (SERIAL_NUMBER BETWEEN 521 AND 529)
--    ORDER BY TURBIDITY ASC, SERIAL_NUMBER DESC;
   UNION 
 SELECT PLACE AS 地點,
  SERIAL_NUMBER AS 序號,
  HYDROGEN AS 氫離子濃度指數,
  TURBIDITY AS 濁度,
  CHLORINE AS 自由有效餘氯
   FROM SQL_TAOYUAN_WATER
   WHERE
   CHLORINE IN(0.76,0.77,0.66) AND HYDROGEN != 7.8 AND TURBIDITY = 0.6
   )
  ORDER BY 濁度 ASC, 序號 DESC;
   
   
SELECT MANUFACTURER,COUNT(*) FROM CARS GROUP BY MANUFACTURER
SELECT COUNT(*)FROM CARS

SELECT * FROM CARS
 ORDER BY PRICE, TYPE DESC;
 
SELECT *
 FROM SQL_EMP
 WHERE EMP_ID IN (SELECT DISTINCT EMP FROM SQL_CUSTOMER);

SELECT EMP_NM, ID FROM SQL_EMP
 UNION 
 SELECT NAME, ID FROM SQL_CUSTOMER;
