const metroObject = {
green: [
    {name:'新店', order:'G01', transferLines:[]},
    {name:'新店區公所', order:'G02', transferLines:[]},
    {name:'七張', order:'G03', transferLines:[]},
    {name:'大坪林', order:'G04', transferLines:['yellow']},
    {name:'景美', order:'G05', transferLines:[]},
    {name:'萬隆', order:'G06', transferLines:[]},
    {name:'公館', order:'G07', transferLines:[]},
    {name:'台電大樓', order:'G08', transferLines:[]},
    {name:'古亭', order:'G09', transferLines:[]},
    {name:'中正紀念堂', order:'G10', transferLines:[]},
    {name:'小南門', order:'G11', transferLines:[]},
    {name:'西門', order:'G12', transferLines:[]},
    {name:'北門', order:'G13', transferLines:[]},
    {name:'中山', order:'G14', transferLines:[]},
    {name:'松江南京', order:'G15', transferLines:[]},
    {name:'南京復興', order:'G16', transferLines:['brown']},
    {name:'台北小巨蛋', order:'G17', transferLines:[]},
    {name:'南京三民', order:'G18', transferLines:[]},
    {name:'松山', order:'G19', transferLines:[]},
],
brown:[
    {name:'動物園', order:'BR01', transferLines:[]},
    {name:'木柵', order:'BR02', transferLines:[]},
    {name:'萬芳社區', order:'BR03', transferLines:[]},
    {name:'萬芳醫院', order:'BR04', transferLines:[]},
    {name:'辛亥', order:'BR05', transferLines:[]},
    {name:'麟光', order:'BR06', transferLines:[]},
    {name:'六張犁', order:'BR07', transferLines:[]},
    {name:'科技大樓', order:'BR08', transferLines:[]},
    {name:'大安', order:'BR09', transferLines:[]},
    {name:'忠孝復興', order:'BR10', transferLines:[]},
    {name:'南京復興', order:'BR11', transferLines:[]},
    {name:'中山國中', order:'BR12', transferLines:[]},
    {name:'松山機場', order:'BR13', transferLines:[]},
    {name:'大直', order:'BR14', transferLines:[]},
    {name:'劍南路', order:'BR15', transferLines:[]},
    {name:'西湖', order:'BR16', transferLines:[]},
    {name:'新店', order:'BR17', transferLines:[]},
    {name:'新店', order:'BR18', transferLines:[]},
    {name:'新店', order:'BR19', transferLines:[]},
    {name:'新店', order:'BR20', transferLines:[]},
    {name:'新店', order:'BR21', transferLines:[]},
    {name:'新店', order:'BR22', transferLines:[]},
    {name:'新店', order:'BR23', transferLines:[]},
    {name:'新店', order:'BR24', transferLines:[]},
],
yellow:[

],
}